"use client";
import { useLiveQuery } from "dexie-react-hooks";
import { AlertTriangle, CheckCircle2, RefreshCw } from "lucide-react";
import { listSynchronizationQueue } from "@/services/offline/query-service";
import { useOffline } from "@/components/shop/offline-provider";
import { PageHeading } from "@/components/ui/page-heading";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
export function SynchronizationView(){const {online,syncing,syncNow,lastSyncAt}=useOffline();const queue=useLiveQuery(() => listSynchronizationQueue(), [], [])??[];return <><PageHeading title="Synchronization" description="Review locally queued records and safely submit them to Postgres." actions={<Button onClick={()=>void syncNow()} disabled={!online||syncing}><RefreshCw className={`h-4 w-4 ${syncing?"animate-spin":""}`}/>Sync now</Button>}/><div className="grid gap-4 lg:grid-cols-3"><Card className="p-5"><p className="text-sm text-slate-500">Connection</p><p className="mt-2 text-xl font-black">{online?"Online":"Offline"}</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Last successful sync</p><p className="mt-2 text-base font-black">{lastSyncAt?new Date(lastSyncAt).toLocaleString():"Never"}</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Queue records</p><p className="mt-2 text-xl font-black">{queue.length}</p></Card></div><Card className="mt-4"><CardHeader><h2 className="font-extrabold">Pending and conflict queue</h2></CardHeader><CardContent>{queue.length?<div className="space-y-2">{queue.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><div className="flex items-center gap-3">{item.status==="CONFLICT"?<AlertTriangle className="h-5 w-5 text-red-600"/>:<CheckCircle2 className="h-5 w-5 text-amber-600"/>}<div><p className="text-sm font-bold">Sale {item.entityId.slice(0,8).toUpperCase()}</p><p className="text-xs text-slate-500">Attempts: {item.attempts}{item.lastError?` • ${item.lastError}`:""}</p></div></div><Badge tone={item.status==="CONFLICT"?"danger":"warning"}>{item.status.replaceAll("_"," ")}</Badge></div>)}</div>:<p className="py-10 text-center text-sm text-slate-400">The local synchronization queue is clear.</p>}</CardContent></Card></>}
