"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { updateEtimsConfigurationAction, updateTaxSettingsAction } from "@/actions/admin/etims-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export function TaxSettingsForm({ settings }: { settings: { vatEnabled: boolean; standardVatRate: number; priceTaxMode: "VAT_EXCLUSIVE" | "VAT_INCLUSIVE"; allowShopEtimsCheckout: boolean } }) {
  const [pending, startTransition] = useTransition();
  return <Card className="mt-4"><CardHeader><div><h2 className="font-extrabold">Tax / VAT</h2><p className="text-sm text-slate-500">These values are authoritative for eTIMS checkout. Historical sales retain their applied VAT values.</p></div></CardHeader><CardContent><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(async () => { try { await updateTaxSettingsAction(data); toast.success("VAT settings saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save VAT settings"); } }); }} className="grid gap-4 md:grid-cols-2"><label className="flex items-center gap-2 text-sm font-semibold md:col-span-2"><input name="vatEnabled" type="checkbox" defaultChecked={settings.vatEnabled} />Enable VAT for eTIMS checkout</label><div><label className="mb-1 block text-xs font-bold text-slate-600">Standard VAT rate (%)</label><Input name="standardVatRate" type="number" step="0.01" min="0" max="100" defaultValue={settings.standardVatRate} required /></div><div><label className="mb-1 block text-xs font-bold text-slate-600">Product price tax mode</label><select name="priceTaxMode" defaultValue={settings.priceTaxMode} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="VAT_EXCLUSIVE">VAT exclusive</option><option value="VAT_INCLUSIVE">VAT inclusive</option></select></div><label className="flex items-center gap-2 text-sm font-semibold md:col-span-2"><input name="allowShopEtimsCheckout" type="checkbox" defaultChecked={settings.allowShopEtimsCheckout} />Allow shop cashier accounts to use eTIMS checkout when their shop is configured</label><div className="md:col-span-2"><Button type="submit" disabled={pending} isLoading={pending} loadingText="Saving VAT settings...">Save VAT settings</Button></div></form></CardContent></Card>;
}

export function EtimsConfigurationForm({ shops, configurations }: { shops: Array<{ id: string; name: string }>; configurations: Array<{ shopId: string; enabled: boolean; integrationMode: "OSCU" | "VSCU"; taxpayerPin?: string | null; branchCode?: string | null; deviceId?: string | null; credentialReference?: string | null }> }) {
  const [pendingShop, setPendingShop] = useState<string | null>(null);
  return <Card className="mt-4"><CardHeader><div><h2 className="font-extrabold">eTIMS shop configuration</h2><p className="text-sm text-slate-500">Store identification values and a server-side credential reference only. Never place a KRA communication key or token in this form.</p></div></CardHeader><CardContent className="space-y-5">{shops.map((shop) => { const config = configurations.find((entry) => entry.shopId === shop.id); const pending = pendingShop === shop.id; return <form key={shop.id} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setPendingShop(shop.id); void updateEtimsConfigurationAction(data).then(() => toast.success(`${shop.name} eTIMS configuration saved`)).catch((error) => toast.error(error instanceof Error ? error.message : "Unable to save configuration")).finally(() => setPendingShop(null)); }} className="grid gap-3 rounded-2xl border border-slate-200 p-4 md:grid-cols-2"><input type="hidden" name="shopId" value={shop.id} /><div className="md:col-span-2 flex items-center justify-between"><p className="font-bold">{shop.name}</p><label className="flex items-center gap-2 text-sm"><input name="enabled" type="checkbox" defaultChecked={config?.enabled ?? false} />Enable for this shop</label></div><div><label className="mb-1 block text-xs font-bold text-slate-600">Integration mode</label><select name="integrationMode" defaultValue={config?.integrationMode ?? "OSCU"} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="OSCU">OSCU (online)</option><option value="VSCU">VSCU (approved offline-capable deployment)</option></select></div><div><label className="mb-1 block text-xs font-bold text-slate-600">Taxpayer PIN</label><Input name="taxpayerPin" defaultValue={config?.taxpayerPin ?? ""} /></div><div><label className="mb-1 block text-xs font-bold text-slate-600">Branch code</label><Input name="branchCode" defaultValue={config?.branchCode ?? ""} /></div><div><label className="mb-1 block text-xs font-bold text-slate-600">Device / terminal ID</label><Input name="deviceId" defaultValue={config?.deviceId ?? ""} /></div><div className="md:col-span-2"><label className="mb-1 block text-xs font-bold text-slate-600">Secure credential reference</label><Input name="credentialReference" defaultValue={config?.credentialReference ?? ""} placeholder="Server secret manager reference — never paste the credential" /></div><div className="md:col-span-2"><Button type="submit" disabled={pending} isLoading={pending} loadingText="Saving shop configuration...">Save {shop.name} configuration</Button></div></form>; })}</CardContent></Card>;
}