import { requireAdmin } from "@/lib/rbac";
import { formatMoney } from "@/lib/utils";
import { getProcurementManagementData } from "@/services/procurement/procurement-service";
import {
  approvePurchaseOrderAction,
  approveRequisitionAction,
  createAdminRequisitionAction,
  createPurchaseOrderAction,
  generateRequisitionsAction,
  receiveGoodsAdminAction,
  recordSupplierPaymentAction,
  rejectRequisitionAction,
  sendPurchaseOrderAction,
  submitPurchaseOrderAction,
} from "@/actions/admin/procurement-actions";
import { GoodsReceiptForm, PurchaseOrderForm, RequisitionForm } from "@/components/procurement/workflow-forms";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeading } from "@/components/ui/page-heading";

export const dynamic = "force-dynamic";

function tone(status: string) {
  if (["APPROVED", "SENT", "FULLY_RECEIVED", "PAID"].includes(status)) return "success" as const;
  if (["REJECTED", "CANCELLED"].includes(status)) return "danger" as const;
  if (["DRAFT"].includes(status)) return "neutral" as const;
  return "warning" as const;
}

export default async function ProcurementPage() {
  const user = await requireAdmin();
  const data = await getProcurementManagementData(user.businessId);
  const actionableOrders = data.purchaseOrders.filter((order) => ["APPROVED", "SENT", "PARTIALLY_RECEIVED"].includes(order.status));
  return <>
    <PageHeading title="Procurement" description="Controlled requisitions, purchase orders, goods receiving, and supplier balances across every shop." actions={<form action={generateRequisitionsAction}><Button variant="secondary">Create requests from active alerts</Button></form>} />
    <div className="grid gap-5 2xl:grid-cols-2">
      <Card><CardHeader><div><h2 className="font-extrabold">New requisition</h2><p className="text-sm text-slate-500">Start with the shop’s actual stock requirement, then send it for approval.</p></div></CardHeader><CardContent><RequisitionForm action={createAdminRequisitionAction} shops={data.shops} suppliers={data.suppliers} products={data.products} /></CardContent></Card>
      <Card><CardHeader><div><h2 className="font-extrabold">New purchase order</h2><p className="text-sm text-slate-500">Draft the commercial terms before submitting and emailing the supplier.</p></div></CardHeader><CardContent><PurchaseOrderForm action={createPurchaseOrderAction} shops={data.shops} suppliers={data.suppliers} products={data.products} requisitions={data.requisitions.filter((request) => request.status === "APPROVED").map((request) => ({ id: request.id, requisitionNumber: request.requisitionNumber, shopId: request.shopId, supplierId: request.supplierId, items: request.items as Array<{ id: string; productId: string; unitId?: string | null; requestedQuantity: number }> }))} /></CardContent></Card>
    </div>

    <Card className="mt-5 overflow-hidden"><CardHeader><div><h2 className="font-extrabold">Requisition approval queue</h2><p className="text-sm text-slate-500">A purchase order cannot be created from a shop request until it has been approved.</p></div></CardHeader><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Request</th><th>Shop / supplier</th><th>Items</th><th>Status</th><th>Requested</th><th>Decision</th></tr></thead><tbody>{data.requisitions.map((request) => <tr key={request.id}><td><p className="font-bold">{request.requisitionNumber}</p><p className="text-xs text-slate-500">{request.reason || "No reason recorded"}</p></td><td>{request.shop?.name ?? "Shop"}<p className="text-xs text-slate-500">{request.supplier?.name ?? "Supplier to be chosen"}</p></td><td>{request.items.map((item: { id: string; productName: string; requestedQuantity: number }) => <p key={item.id} className="text-xs">{item.productName} × {item.requestedQuantity}</p>)}</td><td><Badge tone={tone(request.status)}>{request.status.replaceAll("_", " ")}</Badge></td><td>{request.createdAt?.toLocaleDateString("en-KE")}</td><td>{request.status === "SUBMITTED" ? <div className="flex flex-wrap gap-2"><form action={approveRequisitionAction}><input type="hidden" name="requisitionId" value={request.id} /><Button size="sm">Approve</Button></form><form action={rejectRequisitionAction} className="flex gap-1"><input type="hidden" name="requisitionId" value={request.id} /><Input name="note" className="h-8 w-32" placeholder="Reason" required /><Button size="sm" variant="secondary" className="text-red-700 hover:bg-red-50">Reject</Button></form></div> : <span className="text-xs text-slate-500">{request.approvedAt ? `Approved ${request.approvedAt.toLocaleDateString("en-KE")}` : "No action"}</span>}</td></tr>)}</tbody></table></div></Card>

    <Card className="mt-5 overflow-hidden"><CardHeader><div><h2 className="font-extrabold">Purchase orders</h2><p className="text-sm text-slate-500">Draft → approval → supplier email → partial or full receipt.</p></div></CardHeader><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Order</th><th>Shop / supplier</th><th>Total</th><th>Status</th><th>Items</th><th>Next step</th></tr></thead><tbody>{data.purchaseOrders.map((order) => <tr key={order.id}><td className="font-bold">{order.purchaseOrderNumber}</td><td>{order.shop?.name ?? "Shop"}<p className="text-xs text-slate-500">{order.supplier?.name ?? "Supplier"}</p></td><td>{formatMoney(order.grandTotal, "KES")}</td><td><Badge tone={tone(order.status)}>{order.status.replaceAll("_", " ")}</Badge></td><td>{order.items.map((item: { id: string; productName: string; receivedQuantity: number; orderedQuantity: number }) => <p key={item.id} className="text-xs">{item.productName}: {item.receivedQuantity}/{item.orderedQuantity}</p>)}</td><td><div className="flex flex-wrap items-center gap-2"><a href={`/api/purchase-orders/${order.id}/pdf`} className="text-xs font-medium text-blue-700 underline">PDF</a>{order.status === "DRAFT" ? <form action={submitPurchaseOrderAction}><input type="hidden" name="purchaseOrderId" value={order.id} /><Button size="sm">Submit</Button></form> : order.status === "PENDING_APPROVAL" ? <form action={approvePurchaseOrderAction}><input type="hidden" name="purchaseOrderId" value={order.id} /><Button size="sm">Approve</Button></form> : order.status === "APPROVED" ? <form action={sendPurchaseOrderAction}><input type="hidden" name="purchaseOrderId" value={order.id} /><Button size="sm">Email supplier</Button></form> : <span className="text-xs text-slate-500">{order.status === "FULLY_RECEIVED" ? "Complete" : "Awaiting receipt"}</span>}</div></td></tr>)}</tbody></table></div></Card>

    <Card className="mt-5"><CardHeader><div><h2 className="font-extrabold">Goods receiving</h2><p className="text-sm text-slate-500">Record accepted, damaged, and rejected quantities. Accepted goods update stock and weighted cost immediately.</p></div></CardHeader><CardContent className="space-y-5">{actionableOrders.length ? actionableOrders.map((order) => <div key={order.id} className="rounded-xl border p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">{order.purchaseOrderNumber}</p><p className="text-sm text-slate-500">{order.shop?.name} · {order.supplier?.name}</p></div><Badge tone={tone(order.status)}>{order.status.replaceAll("_", " ")}</Badge></div><GoodsReceiptForm action={receiveGoodsAdminAction} order={{ id: order.id, items: order.items as Array<{ id: string; productName: string; orderedQuantity: number; receivedQuantity: number }> }} /></div>) : <p className="text-sm text-slate-500">No approved or dispatched purchase orders are awaiting receipt.</p>}</CardContent></Card>

    <Card className="mt-5 overflow-hidden"><CardHeader><div><h2 className="font-extrabold">Goods received note history</h2><p className="text-sm text-slate-500">Every finalized receipt records accepted, damaged and rejected quantities before stock is updated.</p></div></CardHeader><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>GRN</th><th>PO / supplier</th><th>Shop</th><th>Accepted / damaged / rejected</th><th>Received</th><th>Payable</th></tr></thead><tbody>{data.goodsReceivedNotes.map((note) => <tr key={note.id}><td><p className="font-bold">{note.goodsReceivedNumber}</p><p className="text-xs text-slate-500">{note.status}</p></td><td>{note.purchaseOrder?.purchaseOrderNumber ?? "Purchase order"}<p className="text-xs text-slate-500">{note.supplier?.name ?? "Supplier"}</p></td><td>{note.shop?.name ?? "Shop"}</td><td>{note.items.map((item: { id: string; acceptedQuantity: number; damagedQuantity: number; rejectedQuantity: number; product?: { name?: string | null } | null }) => <p key={item.id} className="text-xs">{item.product?.name ?? "Product"}: {item.acceptedQuantity} / {item.damagedQuantity} / {item.rejectedQuantity}</p>)}</td><td>{note.receivedAt.toLocaleString("en-KE")}<p className="text-xs text-slate-500">User {note.receivedById}</p></td><td>{note.payable ? formatMoney(note.payable.outstandingAmount, "KES") : "No balance"}</td></tr>)}</tbody></table></div></Card>
    <Card className="mt-5 overflow-hidden"><CardHeader><div><h2 className="font-extrabold">Supplier payables</h2><p className="text-sm text-slate-500">Balances are created only from accepted goods on a finalized goods-received note.</p></div></CardHeader><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Payable</th><th>Supplier / shop</th><th>GRN</th><th>Outstanding</th><th>Status</th><th>Record payment</th></tr></thead><tbody>{data.payables.map((payable) => <tr key={payable.id}><td className="font-bold">{payable.payableNumber}</td><td>{payable.supplier?.name ?? "Supplier"}<p className="text-xs text-slate-500">{payable.shop?.name ?? "Shop"}</p></td><td>{payable.goodsReceivedNote?.goodsReceivedNumber ?? "-"}</td><td>{formatMoney(payable.outstandingAmount, "KES")}</td><td><Badge tone={tone(payable.status)}>{payable.status.replaceAll("_", " ")}</Badge></td><td>{["OPEN", "PARTIALLY_PAID"].includes(payable.status) ? <form action={recordSupplierPaymentAction} className="flex flex-wrap gap-2"><input type="hidden" name="supplierPayableId" value={payable.id} /><Input name="amount" className="h-8 w-24" type="number" min="0.01" max={payable.outstandingAmount} step="0.01" required /><select name="method" className="rounded-lg border px-2 text-xs"><option value="MPESA">M-Pesa</option><option value="BANK_TRANSFER">Bank</option><option value="CASH">Cash</option><option value="CARD">Card</option></select><Input name="reference" className="h-8 w-28" placeholder="Reference" /><Button size="sm">Pay</Button></form> : <span className="text-xs text-emerald-700">Settled</span>}</td></tr>)}</tbody></table></div></Card>
  </>;
}