export type RelationDefinition = {
  target: string;
  localField: string;
  foreignField: string;
  many: boolean;
};

const relation = (
  target: string,
  localField: string,
  foreignField: string,
  many = false,
): RelationDefinition => ({ target, localField, foreignField, many });

export const modelRelations: Record<string, Record<string, RelationDefinition>> = {
  business: {
    shops: relation("shop", "id", "businessId", true),
    users: relation("user", "id", "businessId", true),
    categories: relation("category", "id", "businessId", true),
    brands: relation("brand", "id", "businessId", true),
    units: relation("unit", "id", "businessId", true),
    products: relation("product", "id", "businessId", true),
    inventoryReports: relation("inventoryReport", "id", "businessId", true),
    notificationPreference: relation("notificationPreference", "id", "businessId"),
    expenseCategories: relation("expenseCategory", "id", "businessId", true),
    suppliers: relation("supplier", "id", "businessId", true),
    supplierNotificationHistory: relation("supplierNotificationHistory", "id", "businessId", true),
    taxSettings: relation("taxSettings", "id", "businessId"),
    etimsConfigurations: relation("etimsConfiguration", "id", "businessId", true),
    etimsTransactions: relation("etimsTransaction", "id", "businessId", true),
    purchaseRequisitions: relation("purchaseRequisition", "id", "businessId", true),
    purchaseOrders: relation("purchaseOrder", "id", "businessId", true),
    goodsReceivedNotes: relation("goodsReceivedNote", "id", "businessId", true),
    supplierPayables: relation("supplierPayable", "id", "businessId", true),
    stocktakes: relation("stocktake", "id", "businessId", true),
  },
  shop: {
    business: relation("business", "businessId", "id"),
    account: relation("user", "id", "shopId"),
    salespeople: relation("salespersonProfile", "id", "shopId", true),
    inventory: relation("shopInventory", "id", "shopId", true),
    suppliers: relation("supplier", "id", "shopId", true),
    supplierProducts: relation("supplierProduct", "id", "shopId", true),
    supplierNotificationHistory: relation("supplierNotificationHistory", "id", "shopId", true),
    sales: relation("sale", "id", "shopId", true),
    registers: relation("register", "id", "shopId", true),
    registerSessions: relation("registerSession", "id", "shopId", true),
    stockMovements: relation("stockMovement", "id", "shopId", true),
    outgoingTransfers: relation("stockTransfer", "id", "sourceShopId", true),
    incomingTransfers: relation("stockTransfer", "id", "destinationShopId", true),
    inventoryAlerts: relation("inventoryAlert", "id", "shopId", true),
    expenses: relation("expense", "id", "shopId", true),
    devices: relation("offlineDevice", "id", "shopId", true),
    syncBatches: relation("offlineSyncBatch", "id", "shopId", true),
    conflicts: relation("offlineSyncConflict", "id", "shopId", true),
    notifications: relation("notification", "id", "shopId", true),
    auditLogs: relation("auditLog", "id", "shopId", true),
    idempotency: relation("idempotencyRecord", "id", "shopId", true),
    reportItems: relation("inventoryReportItem", "id", "shopId", true),
    refundRequests: relation("refundRequest", "id", "shopId", true),
    etimsConfiguration: relation("etimsConfiguration", "id", "shopId"),
    etimsTransactions: relation("etimsTransaction", "id", "shopId", true),
    purchaseRequisitions: relation("purchaseRequisition", "id", "shopId", true),
    purchaseOrders: relation("purchaseOrder", "id", "shopId", true),
    goodsReceivedNotes: relation("goodsReceivedNote", "id", "shopId", true),
    supplierPayables: relation("supplierPayable", "id", "shopId", true),
    supplierPayments: relation("supplierPayment", "id", "shopId", true),
    stocktakes: relation("stocktake", "id", "shopId", true),
  },
  user: {
    business: relation("business", "businessId", "id"),
    shop: relation("shop", "shopId", "id"),
    createdBy: relation("user", "createdById", "id"),
    createdUsers: relation("user", "id", "createdById", true),
    pushSubscriptions: relation("pushSubscription", "id", "userId", true),
    notifications: relation("notification", "id", "userId", true),
    auditLogs: relation("auditLog", "id", "userId", true),
  },
  salespersonProfile: {
    shop: relation("shop", "shopId", "id"),
    register: relation("register", "registerId", "id"),
    biometricCredentials: relation("salespersonBiometricCredential", "id", "salespersonId", true),
    biometricChallenges: relation("salespersonBiometricChallenge", "id", "salespersonId", true),
    sales: relation("sale", "id", "salespersonId", true),
    sessions: relation("registerSession", "id", "salespersonId", true),
  },
  category: {
    business: relation("business", "businessId", "id"),
    products: relation("product", "id", "categoryId", true),
  },
  brand: {
    business: relation("business", "businessId", "id"),
    products: relation("product", "id", "brandId", true),
  },
  unit: {
    business: relation("business", "businessId", "id"),
    products: relation("product", "id", "unitId", true),
    pricingUnits: relation("productPricingUnit", "id", "unitId", true),
  },
  product: {
    business: relation("business", "businessId", "id"),
    category: relation("category", "categoryId", "id"),
    brand: relation("brand", "brandId", "id"),
    unit: relation("unit", "unitId", "id"),
    pricingUnits: relation("productPricingUnit", "id", "productId", true),
    inventory: relation("shopInventory", "id", "productId", true),
    supplierProducts: relation("supplierProduct", "id", "productId", true),
    saleItems: relation("saleItem", "id", "productId", true),
    stockMovements: relation("stockMovement", "id", "productId", true),
    transferItems: relation("stockTransferItem", "id", "productId", true),
    inventoryAlerts: relation("inventoryAlert", "id", "productId", true),
    reportItems: relation("inventoryReportItem", "id", "productId", true),
    refundItems: relation("refundItem", "id", "productId", true),
    requisitionItems: relation("purchaseRequisitionItem", "id", "productId", true),
    purchaseOrderItems: relation("purchaseOrderItem", "id", "productId", true),
    goodsReceivedItems: relation("goodsReceivedNoteItem", "id", "productId", true),
    stocktakeItems: relation("stocktakeItem", "id", "productId", true),
  },
  shopInventory: {
    shop: relation("shop", "shopId", "id"),
    product: relation("product", "productId", "id"),
  },
  supplier: {
    business: relation("business", "businessId", "id"),
    shop: relation("shop", "shopId", "id"),
    supplierProducts: relation("supplierProduct", "id", "supplierId", true),
    notificationHistory: relation("supplierNotificationHistory", "id", "supplierId", true),
    purchaseRequisitions: relation("purchaseRequisition", "id", "supplierId", true),
    purchaseOrders: relation("purchaseOrder", "id", "supplierId", true),
    goodsReceivedNotes: relation("goodsReceivedNote", "id", "supplierId", true),
    payables: relation("supplierPayable", "id", "supplierId", true),
    payments: relation("supplierPayment", "id", "supplierId", true),
  },
  purchaseRequisition: {
    shop: relation("shop", "shopId", "id"),
    supplier: relation("supplier", "supplierId", "id"),
    items: relation("purchaseRequisitionItem", "id", "requisitionId", true),
    purchaseOrder: relation("purchaseOrder", "convertedPurchaseOrderId", "id"),
  },
  purchaseRequisitionItem: {
    requisition: relation("purchaseRequisition", "requisitionId", "id"),
    product: relation("product", "productId", "id"),
    unit: relation("unit", "unitId", "id"),
  },
  purchaseOrder: {
    shop: relation("shop", "shopId", "id"),
    supplier: relation("supplier", "supplierId", "id"),
    requisition: relation("purchaseRequisition", "requisitionId", "id"),
    items: relation("purchaseOrderItem", "id", "purchaseOrderId", true),
    goodsReceivedNotes: relation("goodsReceivedNote", "id", "purchaseOrderId", true),
    payables: relation("supplierPayable", "id", "purchaseOrderId", true),
  },
  purchaseOrderItem: {
    purchaseOrder: relation("purchaseOrder", "purchaseOrderId", "id"),
    product: relation("product", "productId", "id"),
    unit: relation("unit", "unitId", "id"),
  },
  goodsReceivedNote: {
    shop: relation("shop", "shopId", "id"),
    supplier: relation("supplier", "supplierId", "id"),
    purchaseOrder: relation("purchaseOrder", "purchaseOrderId", "id"),
    items: relation("goodsReceivedNoteItem", "id", "goodsReceivedNoteId", true),
    payable: relation("supplierPayable", "id", "goodsReceivedNoteId"),
  },
  goodsReceivedNoteItem: {
    goodsReceivedNote: relation("goodsReceivedNote", "goodsReceivedNoteId", "id"),
    purchaseOrderItem: relation("purchaseOrderItem", "purchaseOrderItemId", "id"),
    product: relation("product", "productId", "id"),
  },
  supplierPayable: {
    supplier: relation("supplier", "supplierId", "id"),
    shop: relation("shop", "shopId", "id"),
    purchaseOrder: relation("purchaseOrder", "purchaseOrderId", "id"),
    goodsReceivedNote: relation("goodsReceivedNote", "goodsReceivedNoteId", "id"),
    payments: relation("supplierPayment", "id", "supplierPayableId", true),
  },
  supplierPayment: {
    payable: relation("supplierPayable", "supplierPayableId", "id"),
    supplier: relation("supplier", "supplierId", "id"),
    shop: relation("shop", "shopId", "id"),
  },
  stocktake: {
    shop: relation("shop", "shopId", "id"),
    items: relation("stocktakeItem", "id", "stocktakeId", true),
  },
  stocktakeItem: {
    stocktake: relation("stocktake", "stocktakeId", "id"),
    product: relation("product", "productId", "id"),
  },
  customer: {
    shop: relation("shop", "shopId", "id"),
  },
  supplierProduct: {
    supplier: relation("supplier", "supplierId", "id"),
    shop: relation("shop", "shopId", "id"),
    product: relation("product", "productId", "id"),
  },
  supplierNotificationHistory: {
    supplier: relation("supplier", "supplierId", "id"),
    shop: relation("shop", "shopId", "id"),
    business: relation("business", "businessId", "id"),
  },
  register: {
    shop: relation("shop", "shopId", "id"),
    sessions: relation("registerSession", "id", "registerId", true),
  },
  registerSession: {
    shop: relation("shop", "shopId", "id"),
    register: relation("register", "registerId", "id"),
    salesperson: relation("salespersonProfile", "salespersonId", "id"),
    sales: relation("sale", "id", "registerSessionId", true),
    transactions: relation("registerTransaction", "id", "registerSessionId", true),
  },
  registerTransaction: {
    registerSession: relation("registerSession", "registerSessionId", "id"),
  },
  sale: {
    shop: relation("shop", "shopId", "id"),
    registerSession: relation("registerSession", "registerSessionId", "id"),
    salesperson: relation("salespersonProfile", "salespersonId", "id"),
    items: relation("saleItem", "id", "saleId", true),
    payments: relation("payment", "id", "saleId", true),
    refundRequests: relation("refundRequest", "id", "saleId", true),
    refunds: relation("refund", "id", "saleId", true),
    etimsTransaction: relation("etimsTransaction", "id", "saleId"),
  },
  saleItem: {
    sale: relation("sale", "saleId", "id"),
    product: relation("product", "productId", "id"),
  },
  payment: { sale: relation("sale", "saleId", "id") },
  taxSettings: { business: relation("business", "businessId", "id") },
  etimsConfiguration: { business: relation("business", "businessId", "id"), shop: relation("shop", "shopId", "id") },
  etimsTransaction: { sale: relation("sale", "saleId", "id"), shop: relation("shop", "shopId", "id"), business: relation("business", "businessId", "id") },
  stockMovement: {
    shop: relation("shop", "shopId", "id"),
    product: relation("product", "productId", "id"),
  },
  stockTransfer: {
    sourceShop: relation("shop", "sourceShopId", "id"),
    destinationShop: relation("shop", "destinationShopId", "id"),
    items: relation("stockTransferItem", "id", "transferId", true),
  },
  productPricingUnit: {
    product: relation("product", "productId", "id"),
    unit: relation("unit", "unitId", "id"),
  },
  stockTransferItem: {
    transfer: relation("stockTransfer", "transferId", "id"),
    product: relation("product", "productId", "id"),
  },
  inventoryAlert: {
    shop: relation("shop", "shopId", "id"),
    product: relation("product", "productId", "id"),
  },
  inventoryReport: {
    business: relation("business", "businessId", "id"),
    items: relation("inventoryReportItem", "id", "reportId", true),
  },
  inventoryReportItem: {
    report: relation("inventoryReport", "reportId", "id"),
    shop: relation("shop", "shopId", "id"),
    product: relation("product", "productId", "id"),
  },
  refundRequest: {
    sale: relation("sale", "saleId", "id"),
    shop: relation("shop", "shopId", "id"),
  },
  refund: {
    sale: relation("sale", "saleId", "id"),
    items: relation("refundItem", "id", "refundId", true),
  },
  refundItem: {
    refund: relation("refund", "refundId", "id"),
    product: relation("product", "productId", "id"),
  },
  expenseCategory: {
    business: relation("business", "businessId", "id"),
    expenses: relation("expense", "id", "categoryId", true),
  },
  expense: {
    shop: relation("shop", "shopId", "id"),
    category: relation("expenseCategory", "categoryId", "id"),
  },
  notification: {
    user: relation("user", "userId", "id"),
    shop: relation("shop", "shopId", "id"),
  },
  notificationPreference: {
    business: relation("business", "businessId", "id"),
  },
  pushSubscription: {
    user: relation("user", "userId", "id"),
  },
  offlineDevice: {
    shop: relation("shop", "shopId", "id"),
    syncBatches: relation("offlineSyncBatch", "id", "deviceId", true),
    conflicts: relation("offlineSyncConflict", "id", "deviceId", true),
  },
  offlineSyncBatch: {
    shop: relation("shop", "shopId", "id"),
    device: relation("offlineDevice", "deviceId", "id"),
  },
  offlineSyncConflict: {
    shop: relation("shop", "shopId", "id"),
    device: relation("offlineDevice", "deviceId", "id"),
  },
  idempotencyRecord: { shop: relation("shop", "shopId", "id") },
  auditLog: {
    user: relation("user", "userId", "id"),
    shop: relation("shop", "shopId", "id"),
  },
};
