import { requireShop } from "@/lib/rbac";
import { cancelStocktakeAction, recordStocktakeCountsAction, startShopStocktakeAction, submitStocktakeAction } from "@/actions/shop/stocktake-actions";
import { StocktakeBarcodeLookup, StocktakeCountForm } from "@/components/procurement/workflow-forms";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeading } from "@/components/ui/page-heading";
import { getShopStocktakeData } from "@/services/stocktake/stocktake-service";

export const dynamic = "force-dynamic";

export default async function ShopStocktakePage() {
  const user = await requireShop(); const data = await getShopStocktakeData(user); const active = data.stocktakes.find((stocktake) => stocktake.status === "COUNTING" || stocktake.status === "DRAFT"); const history = data.stocktakes.filter((stocktake) => stocktake.id !== active?.id);
  return <><PageHeading title="Stocktake" description="Count stock against a frozen snapshot, document variances, then submit it to management for approval." />{active ? <Card><CardHeader><div><h2 className="font-extrabold">{active.stocktakeNumber}</h2><p className="text-sm text-slate-500">System quantities are the snapshot from when the stocktake started; they are not changed while you count.</p></div></CardHeader><CardContent><div className="mb-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Save each count after entering the physical quantity. Significant differences require a variance reason. When every line is counted, submit the stocktake for approval.</div><StocktakeBarcodeLookup /><div>{active.items.map((item: { id: string; productName: string; sku: string; barcode?: string | null; systemQuantity: number; physicalQuantity?: number | null; varianceReason?: string | null; reasonNote?: string | null }) => <StocktakeCountForm key={item.id} action={recordStocktakeCountsAction} stocktakeId={active.id} item={item} />)}</div><div className="mt-4 flex flex-wrap gap-2"><form action={submitStocktakeAction}><input type="hidden" name="stocktakeId" value={active.id} /><Button>Submit for approval</Button></form><form action={cancelStocktakeAction}><input type="hidden" name="stocktakeId" value={active.id} /><Button variant="secondary">Cancel stocktake</Button></form></div></CardContent></Card> : <Card><CardHeader><div><h2 className="font-extrabold">Start a stocktake</h2><p className="text-sm text-slate-500">This creates a count sheet from your shop’s current inventory.</p></div></CardHeader><CardContent><form action={startShopStocktakeAction} className="flex max-w-xl flex-col gap-3"><Input name="notes" maxLength={1000} placeholder="Optional scope or notes" /><div><Button>Start stocktake</Button></div></form></CardContent></Card>}<Card className="mt-5 overflow-hidden"><CardHeader><div><h2 className="font-extrabold">Stocktake history</h2><p className="text-sm text-slate-500">Review past counts and manager decisions for this shop.</p></div></CardHeader><div className="overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Stocktake</th><th>Lines</th><th>Status</th><th>Submitted</th><th>Manager note</th></tr></thead><tbody>{history.map((stocktake) => <tr key={stocktake.id}><td className="font-bold">{stocktake.stocktakeNumber}</td><td>{stocktake.items.length}</td><td><Badge tone={stocktake.status === "COMPLETED" ? "success" : stocktake.status === "REJECTED" ? "danger" : "warning"}>{stocktake.status.replaceAll("_", " ")}</Badge></td><td>{stocktake.submittedAt?.toLocaleDateString("en-KE") ?? "-"}</td><td>{stocktake.rejectionReason ?? "-"}</td></tr>)}</tbody></table></div></Card></>;
}